name: apartment-parser build

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  format-and-lint:
    name: lint
    runs-on: ubuntu-latest
    steps:
      - name: Set up GO
        uses: actions/setup-go@v4
        with:
          go-version: 1.17
          cache: false

      - name: Set up Python
        uses: actions/setup-python@v3

      - name: Checkout
        uses: actions/checkout@v3
        with:
          submodules: recursive

      - name: Pre-commit
        uses: pre-commit/action@v3.0.1

      - name: Lint
        uses: golangci/golangci-lint-action@v3


  build:
    name: build
    runs-on: ubuntu-latest
    steps:
      - name: Set up GO
        uses: actions/setup-go@v4
        with:
          go-version: 1.17
          cache: false

      - name: Checkout
        uses: actions/checkout@v3
        with:
          submodules: recursive

      - name: Build
        run: go build -o apartment-parser .
